import fs from 'fs';
import path from 'path';
import { execFileSync } from 'child_process';
import { expect } from 'chai';
import { FIXTURES_DIR, GENERATED, ROOT } from './helpers';

const CLI = path.join(ROOT, 'dist', 'cli.js');
const SIMPLE = path.join(FIXTURES_DIR, 'simple.fio');

type Run = { status: number, stdout: string }

const run = (...args: Array<string>): Run => {
  try {
    return {
      status: 0,
      stdout: execFileSync('node', [CLI, ...args], { cwd: ROOT, encoding: 'utf8' }),
    };
  } catch (e) {
    const err = e as { status: number, stdout: string };
    return { status: err.status, stdout: err.stdout || '' };
  }
};

//
// These drive the built CLI, so they need `dist`. Skipped rather than failed
// when it is not there: `npm run test:integration` does not build.
//
const built = fs.existsSync(CLI);

(built ? describe : describe.skip)('finitio cli', function() {

  this.timeout(60000);

  const broken = path.join(GENERATED, 'broken.fio');

  before(() => {
    fs.mkdirSync(path.join(ROOT, GENERATED), { recursive: true });
    fs.writeFileSync(
      path.join(ROOT, broken),
      '@import finitio/data\n\nMain = { a: NoSuchType }\n'
    );
  });

  describe('types', () => {

    it('writes declarations to stdout', () => {
      const { status, stdout } = run('types', SIMPLE);

      expect(status).to.eql(0);
      expect(stdout).to.contain('export type Main = {');
      expect(stdout).to.contain('Generated by finitio');
      // no loader, no inlined ast
      expect(stdout).not.to.contain('export default');
      expect(stdout).not.to.contain('importResolver');
    });

    it('writes to a file with --out', () => {
      const out = path.join(GENERATED, 'cli.d.ts');
      const { status } = run('types', SIMPLE, '-o', out);

      expect(status).to.eql(0);
      expect(fs.readFileSync(path.join(ROOT, out)).toString())
        .to.contain('export type Main = {');
    });

    it('honours --brands and --any-as', () => {
      expect(run('types', SIMPLE, '--any-as', 'unknown').stdout)
        .to.contain('export type Any = unknown;');
      expect(run('types', path.join(FIXTURES_DIR, 'brands.fio'), '--brands').stdout)
        .to.contain('FinitioBrand<');
    });

  });

  describe('checking', () => {

    it('refuses a schema that does not compile, and says why', () => {
      const { status, stdout } = run('types', broken);

      expect(status).not.to.eql(0);
      expect(stdout).to.contain('No such type `NoSuchType`');
    });

    it('bundles it only when told not to check', () => {
      expect(run('bundle', '-t', 'typescript', broken).status).not.to.eql(0);
      expect(run('bundle', '-t', 'typescript', '--no-check', broken).status).to.eql(0);
    });

    it('leaves a valid schema alone', () => {
      expect(run('bundle', '-t', 'typescript', SIMPLE).status).to.eql(0);
    });

  });

});
