import fs from 'fs';
import { program, default as Commander } from 'commander';
import type { World } from './finitio';
import { TypeError } from './finitio';
import Finitio from './finitio';
import { TargetLanguage, getBundler } from './finitio/bundlers';
import { generateTypes } from './finitio/generators/typescript';

const options = program.opts();

const DECLARATIONS_PRELUDE = [
  '// Generated by finitio. Do not edit.',
  '//',
  '// Load the schema with `Finitio.system<System0>(source)`, which types',
  '// dressing against these declarations without a cast.',
  'import type * as FinitioTypes from \'finitio\';',
  '',
  '',
].join('\n');

//
// Regenerates on change, over the schema and its transitive imports.
//
// The set of files to watch is whatever the generation just resolved, so it
// grows and shrinks with the `@import`s themselves.
//
const watch = (path: string, generate: () => Array<string>) => {
  let watchers: Array<fs.FSWatcher> = [];
  let pending: NodeJS.Timeout|undefined;
  // The imports of the last generation that got far enough to resolve them.
  // A failed run reports none, and must not narrow the watch to the entry
  // schema -- the fix usually lands in the very import that just broke.
  let known: Array<string> = [];

  const run = () => {
    try {
      known = generate();
      console.error(`[finitio] generated from ${path}`);
    } catch (e) {
      // A broken edit must not end the watch: report it and keep going.
      errorManager(e);
    }
    rewatch(known);
  };

  const rewatch = (urls: Array<string>) => {
    watchers.forEach(w => w.close());
    watchers = [];

    for (const file of watchedFiles(path, urls)) {
      try {
        watchers.push(fs.watch(file, () => {
          // Editors write in bursts; coalesce them.
          if (pending) { clearTimeout(pending); }
          pending = setTimeout(run, 50);
        }));
      } catch (e) {
        console.error(`[finitio] cannot watch ${file}: ${(e as Error).message}`);
      }
    }
  };

  run();
};

//
// The schema itself, plus every `file://` system the last generation pulled
// in.
//
// A `file://` url is not quite a path: `@import ./people` resolves against a
// `people.fio` on disk, but is keyed extensionless, exactly as the import was
// written. The candidates below mirror the file resolver's own.
//
const RESOLVED_EXTENSIONS = ['', '.fio', '.json'];

const existingFile = (base: string): string|undefined =>
  RESOLVED_EXTENSIONS.map(ext => base + ext).find(p => fs.existsSync(p));

const watchedFiles = (path: string, urls: Array<string>): Array<string> => {
  const files = new Set<string>();

  for (const url of [`file://${path}`].concat(urls)) {
    const match = url.match(/^file:\/\/(.*)$/);
    if (!match) { continue; }

    const file = existingFile(match[1]);
    if (file) {
      files.add(file);
    } else {
      console.error(`[finitio] cannot watch: ${match[1]}`);
    }
  }

  return [...files];
};

const world = function(sourceUrl: string, extra?: Record<string, unknown>) {
  const w: World = {
    failfast: options.fast,
    sourceUrl: sourceUrl,
    check: !!options.fast,
    ...extra,
  };
  return w;
};

const schema = function(path: string) {
  return Finitio.system(
    fs.readFileSync(path).toString(),
    world(path)
  );
};

program.version(`finitio.js ${Finitio.VERSION} (c) Bernard, Louis Lambeau & the University of Louvain`)
  .option('-f, --fast', 'Stop on first validation error')
  .option('--stack', 'Show stack trace on error')

  program.command('bundle')
  .description('Bundle the input schema as a loader for the specified target language')
  .option('--url <url>', 'Specify the bundle global url')
  .option('--no-check', 'Do not try to check the system before bundling')
  .option('--prelude <path>', 'Path to a file to include as prelude of the generated bundle')
  .option('--stdlib <path>', 'Set the stdlib path')
  .option('--brands', 'typescript: emit constrained sub types as nominal types')
  .addOption(
    new Commander.Option('--any-as <type>', 'typescript: what Finitio\'s Any maps to')
      .default('any')
      .choices(['any', 'unknown'])
  )
  .addOption(
    new Commander.Option('-t, --target <language>', 'Set the target language')
      .default(TargetLanguage.Javascript)
      .choices(Object.values(TargetLanguage))
    )
  .addArgument(
    new Commander.Argument(
      '<schema>',
      'path to a finitio schema',
    )
  )
  .action((path, options) => {
    const world: World = {
      // `--fast` is declared on the program, not on this command.
      failfast: !!program.opts().fast,
      // `--no-check` gives commander a `check` that defaults to true. It used
      // to be read off `options.fast`, which is never set here, so nothing was
      // ever checked and `--no-check` did nothing.
      check: options.check !== false,
      sourceUrl: options.url || `file://${path}`,
      stdlibPath: options.stdlib,
      typescript: {
        brands: !!options.brands,
        anyAs: options.anyAs,
      },
    }

    const bundle = Finitio.bundleFile(path, world, options.target);
    const prelude = options.prelude ? fs.readFileSync(options.prelude) : ''
    return console.log(
      prelude + '\n' + bundle
    );
  })

program.command('types')
  .description('Generate the TypeScript declarations of a schema')
  .option('-o, --out <path>', 'Write to a file instead of stdout')
  .option('--no-check', 'Do not try to check the system before generating')
  .option('--stdlib <path>', 'Set the stdlib path')
  .option('--brands', 'Emit constrained sub types as nominal types')
  .option('-w, --watch', 'Regenerate when the schema or one of its imports changes')
  .addOption(
    new Commander.Option('--any-as <type>', 'What Finitio\'s Any maps to')
      .default('any')
      .choices(['any', 'unknown'])
  )
  .addArgument(
    new Commander.Argument(
      '<schema>',
      'path to a finitio schema',
    )
  )
  .action((path, options) => {
    // Returns the source urls the schema pulled in, which is what watch mode
    // watches: the set grows and shrinks with the `@import`s themselves.
    const generate = (): Array<string> => {
      const world: World = {
        failfast: !!program.opts().fast,
        check: options.check !== false,
        sourceUrl: `file://${path}`,
        stdlibPath: options.stdlib,
        typescript: {
          brands: !!options.brands,
          anyAs: options.anyAs,
        },
      };

      const bundler = getBundler(TargetLanguage.Typescript, Finitio.world(world));
      bundler.addFile(path);

      const types = DECLARATIONS_PRELUDE + generateTypes(bundler.systems, world.typescript);

      if (options.out) {
        fs.writeFileSync(options.out, types);
      } else {
        console.log(types);
      }

      return Object.keys(bundler.systems);
    };

    if (!options.watch) {
      generate();
      return;
    }

    watch(path, generate);
  })

program.command('validate')
  .description('Validate data against a finitio schema')
  .addArgument(
    new Commander.Argument(
      '<schema>',
      'path to a finitio schema',
    )
  )
  .addArgument(
    new Commander.Argument(
      '<input>',
      'path to json data',
    )
  )
  .action((schemaPath, inputPath) => {
    const s = schema(schemaPath);
    const file = fs.readFileSync(inputPath);
    const data = JSON.parse(file.toString());
    console.log(s.dress(data));
  })

type ErrorMatcher = (err: Error|unknown) => boolean
type ErrorHandler = (err: Error|unknown) => void
type Strategy = [ErrorMatcher, ErrorHandler]
const strategies: Array<Strategy> = [];

const errorManager = function(e) {
  const results: Array<unknown> = [];
  for (let i = 0, len = strategies.length; i < len; i++) {
    const s = strategies[i];
    if (s[0](e)) {
      s[1](e);
      break;
    } else {
      results.push(void 0);
    }
  }
  return results;
};

strategies.push([
  function(e) {
    return e instanceof TypeError;
  }, function(e) {
    const err = e as TypeError;
    if (options.stack) {
      return console.log(err.explainTree());
    } else {
      return console.log(err.explain());
    }
  },
]);

type SyntaxError = Error & {
  line: number,
  column: number
  expected: unknown
}

strategies.push([
  function(e) {
    return (e as Error).name === 'SyntaxError';
  }, function(e) {
    const err = e as SyntaxError;
    console.log(`[${err.line}:${err.column}] ${err.message}`);
    if (options.stack) {
      return console.log(err.expected);
    }
  },
]);

strategies.push([
  function(_e) {
    return true;
  }, function(e) {
    const err = e as Error;
    console.log(err.message);
    if (options.stack) {
      return console.log(err.stack);
    }
  },
]);

try {
  program.parse(process.argv);
} catch (e) {
  errorManager(e);
  // A schema that does not compile must not look like a success: generated
  // output is consumed by build pipelines.
  process.exitCode = 1;
}
