name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      # (TODO: find ways to remove that)
      - run: touch src/finitio/stdlib/data.js
      # (TODO: find ways to remove that need for double builds)
      - run: npm run build
      - name: Build finitio
        run: npm run build
      - name: Run unit tests
        run: npm run test:unit
      - name: Run integration tests
        run: npm run test:integration
      - name: Run acceptance tests
        run: npm run test:acceptance
      - name: Browserify
        run: npm run browserify
